version: "3"
services:
  texlive-ja:
    build: .
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ./.latexmkrc:/root/.latexmkrc
      - ./.vscode:/workdir/.vscode
      - ./.gitignore:/workdir/.gitignore
      - ~/.zhistory:/root/.zsh_history
    environment:
      SHELL: "/bin/zsh"
