version: "3"
services:
  texlive-ja:
    build: .
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ~/.gitconfig:/root/.gitconfig:ro
      - ./.latexmkrc:/root/.latexmkrc
      - ./.vscode:/workdir/.vscode
      - ./.gitignore:/workdir/.gitignore
    environment:
      SHELL: "/bin/zsh"
